# Generated by Django 4.0.5 on 2022-06-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('detail_url', models.URLField()),
            ],
            options={
                'verbose_name': 'PokemonInfo',
                'verbose_name_plural': "Pokemon's Info",
            },
        ),
    ]
