# Generated by Django 4.0.5 on 2022-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeMainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemoninfo',
            name='detail_url',
            field=models.TextField(),
        ),
    ]
