version: "3.9"

services:


  django-app:
    build: .
    container_name: 'django-app'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    depends_on:
      - pgdb


  pgdb:
    image: postgres
    environment:
      POSTGRES_DB: pokemon
      POSTGRES_USER: pokemon
      POSTGRES_PASSWORD: 12345
      POSTGRES_INITDB_ARGS: '-A md5'

    ports:
      - '5432:5432'

    container_name: pgdb






